language: node_js
node_js:
  - 'node'
  - 'lts/*'

script:
- node ./internals/scripts/generate-templates-for-linting
- npm test -- --maxWorkers=4
- npm run build
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  on:
    all_branches: true
    node: 'node'
  api_key:
    secure: ryGjHK6sH4OHF65V2ZDAcTc+wUQVA8PbquSpCZp6DD4K0WnEzqJWwuQbTuBYQoHecK50gy/LAbhMV4O15spdxcsRq0X4sZGUUiYcapG6pT1NPqmqeYrTydzoT77Zd7H/XpSZK02oth6v6o77tvQTcDTVPC0qa2vY6XNj10XBtzCWJFnSz2oS71yZOpngCp7wUAsvGhNEzsWVdEi94rT1OmWnDMzCagO8AQGVAbOE+Bsf/SVuFAtpswqDuwp2YzLA1DhwmODKwIoPTslaRcjSAnC09wvXTJJCujscAozahVEbpgns6qdpTskZoqMwSeD1xDVSKoQB4PcitfjbG+8VQe0uPX8iNUczkdWrfYYMj82bzX7zMeI1WIXK3OmgqkU4Unw0WZ6OTujbHbrFeBmIk016Dg3OTe+PeIMh45UCI/XUyqmaXdduigvujKB4ZtHYQtfA0mV1W7InDgVH7HelFHeFJ8RvHwN9XLH5Z9/zRhKm6qC6XY/RnTdFhSzrhSz4hobZTaUEoYXiEGy8hgpbVCQ5TQLmVzxAcHDRHjso64aldNukyRHZXw61Ns6fH/OWGBP32oi1ZfG9ZqSv/XHNoGqML+JY0ZkUtgUnVOeIkc+MA7ZIYRAmaXTcamXWOrT9ncvnE8A3apIuZlRCzWkjoBOE2hTKBaYhdU+5n29hF5E=
  app:
    master: react-boilerplate-gs
    develop: react-develop-gs
